version: "3"

services:
  monitor:
    image: alext/monitor
    container_name: monitor
    hostname: monitor
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Australia/Brisbane
    privileged: true
    volumes:
      - ./config:/config
    command:
      ["bash", "monitor.sh", "-D", "/config", "-b", "-tr"] #PRIMARY NODE
#       ["bash", "monitor.sh", "-D", "/config", "-tadr"] #HELPER NODE

networks:
  iot:
    external: true
